### ISSUE TITLE
Keyboard inputs don't trigger HandleKeyDown, but mouse inputs do

### ISSUE THREAD

**Issue by KTVX94** [elringus/unity-raw-input#39]
First of all, sorry if I'm doing something dumb, I'm trying to figure out how this works. I have one singular script on my application, it's supposed to just play a random sound when I press a key (which should be the right shift). Right now this is my setup:

![image](https://github.com/user-attachments/assets/5b7fa7ea-c0f7-4302-b60f-d5feed47043e)
![image](https://github.com/user-attachments/assets/f5e11eb7-18a1-41d2-aa92-059bd26f05e7)

When I click any of my mouse buttons or scroll the wheel, I can see "down" on the console and the sound is played, but no key presses do it. I get the same behavior (minus the logs) on an actual build, and it is set to run in the background as well so that's not what I'm missing.

**Comment by elringus** [comment]
Check the sample project in the repo. It should log both the keyboard and mouse event. If it doesn't work as well, it's probably related to either the specific OS/hardware you're running or the Unity version (in case it's different from the one used in the sample project).
